-- P0.8: Seed wards for 5 major cities (Phase 1)
-- HCMC, Hanoi, Da Nang, Can Tho, Hai Phong
-- Compact JSON bulk insert format

INSERT INTO vietnam_administrative_divisions (code, name, name_short, type, level, parent_code)
SELECT code, name, name_short, type, COALESCE(level, 3), parent_code FROM json_to_recordset('[
  {"code":"VN-SG-Q1-BNghe","name":"Phường Bến Nghé","name_short":"Bến Nghé","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-BThanh","name":"Phường Bến Thành","name_short":"Bến Thành","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-CKho","name":"Phường Cầu Kho","name_short":"Cầu Kho","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-COLanh","name":"Phường Cầu Ông Lãnh","name_short":"Cầu Ông Lãnh","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-CGiang","name":"Phường Cô Giang","name_short":"Cô Giang","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-DKao","name":"Phường Đa Kao","name_short":"Đa Kao","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-NCT","name":"Phường Nguyễn Cư Trinh","name_short":"Nguyễn Cư Trinh","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-NTB","name":"Phường Nguyễn Thái Bình","name_short":"Nguyễn Thái Bình","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-PNL","name":"Phường Phạm Ngũ Lão","name_short":"Phạm Ngũ Lão","type":"ward","parent_code":"VN-SG-Q1"},
  {"code":"VN-SG-Q1-TDinh","name":"Phường Tân Định","name_short":"Tân Định","type":"ward","parent_code":"VN-SG-Q1"},

  {"code":"VN-SG-Q3-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q3"},
  {"code":"VN-SG-Q3-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q3"},

  {"code":"VN-SG-Q4-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P16","name":"Phường 16","name_short":"16","type":"ward","parent_code":"VN-SG-Q4"},
  {"code":"VN-SG-Q4-P18","name":"Phường 18","name_short":"18","type":"ward","parent_code":"VN-SG-Q4"},

  {"code":"VN-SG-Q5-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q5"},
  {"code":"VN-SG-Q5-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-Q5"},

  {"code":"VN-SG-Q6-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q6"},
  {"code":"VN-SG-Q6-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q6"},

  {"code":"VN-SG-Q7-BThuan","name":"Phường Bình Thuận","name_short":"Bình Thuận","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-PMy","name":"Phường Phú Mỹ","name_short":"Phú Mỹ","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-PThuan","name":"Phường Phú Thuận","name_short":"Phú Thuận","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-THung","name":"Phường Tân Hưng","name_short":"Tân Hưng","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TKheng","name":"Phường Tân Kiểng","name_short":"Tân Kiểng","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TPhong","name":"Phường Tân Phong","name_short":"Tân Phong","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TPhu","name":"Phường Tân Phú","name_short":"Tân Phú","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TQuy","name":"Phường Tân Quy","name_short":"Tân Quy","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TTDong","name":"Phường Tân Thuận Đông","name_short":"Tân Thuận Đông","type":"ward","parent_code":"VN-SG-Q7"},
  {"code":"VN-SG-Q7-TTTay","name":"Phường Tân Thuận Tây","name_short":"Tân Thuận Tây","type":"ward","parent_code":"VN-SG-Q7"},

  {"code":"VN-SG-Q8-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-Q8"},
  {"code":"VN-SG-Q8-P16","name":"Phường 16","name_short":"16","type":"ward","parent_code":"VN-SG-Q8"},

  {"code":"VN-SG-Q10-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q10"},
  {"code":"VN-SG-Q10-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-Q10"},

  {"code":"VN-SG-Q11-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-Q11"},
  {"code":"VN-SG-Q11-P16","name":"Phường 16","name_short":"16","type":"ward","parent_code":"VN-SG-Q11"},

  {"code":"VN-SG-Q12-APDong","name":"Phường An Phú Đông","name_short":"An Phú Đông","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-DHThuan","name":"Phường Đông Hưng Thuận","name_short":"Đông Hưng Thuận","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-HThanh","name":"Phường Hiệp Thành","name_short":"Hiệp Thành","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TCHiep","name":"Phường Tân Chánh Hiệp","name_short":"Tân Chánh Hiệp","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TThoiH","name":"Phường Tân Hưng Thuận","name_short":"Tân Hưng Thuận","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TTNHiep","name":"Phường Tân Thới Hiệp","name_short":"Tân Thới Hiệp","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TTNhat","name":"Phường Tân Thới Nhất","name_short":"Tân Thới Nhất","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TLoc","name":"Phường Thạnh Lộc","name_short":"Thạnh Lộc","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TXuan","name":"Phường Thạnh Xuân","name_short":"Thạnh Xuân","type":"ward","parent_code":"VN-SG-Q12"},
  {"code":"VN-SG-Q12-TMTay","name":"Phường Trung Mỹ Tây","name_short":"Trung Mỹ Tây","type":"ward","parent_code":"VN-SG-Q12"},

  {"code":"VN-SG-BThanh-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P17","name":"Phường 17","name_short":"17","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P19","name":"Phường 19","name_short":"19","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P21","name":"Phường 21","name_short":"21","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P22","name":"Phường 22","name_short":"22","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P24","name":"Phường 24","name_short":"24","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P25","name":"Phường 25","name_short":"25","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P26","name":"Phường 26","name_short":"26","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P27","name":"Phường 27","name_short":"27","type":"ward","parent_code":"VN-SG-BThanh"},
  {"code":"VN-SG-BThanh-P28","name":"Phường 28","name_short":"28","type":"ward","parent_code":"VN-SG-BThanh"},

  {"code":"VN-SG-PNhuan-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-PNhuan"},
  {"code":"VN-SG-PNhuan-P17","name":"Phường 17","name_short":"17","type":"ward","parent_code":"VN-SG-PNhuan"},

  {"code":"VN-SG-GoVap-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P16","name":"Phường 16","name_short":"16","type":"ward","parent_code":"VN-SG-GoVap"},
  {"code":"VN-SG-GoVap-P17","name":"Phường 17","name_short":"17","type":"ward","parent_code":"VN-SG-GoVap"},

  {"code":"VN-SG-TBinh-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-TBinh"},
  {"code":"VN-SG-TBinh-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-TBinh"},

  {"code":"VN-SG-TPhu-P1","name":"Phường 1","name_short":"1","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P2","name":"Phường 2","name_short":"2","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P3","name":"Phường 3","name_short":"3","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P4","name":"Phường 4","name_short":"4","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P5","name":"Phường 5","name_short":"5","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P6","name":"Phường 6","name_short":"6","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P7","name":"Phường 7","name_short":"7","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P8","name":"Phường 8","name_short":"8","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P9","name":"Phường 9","name_short":"9","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P10","name":"Phường 10","name_short":"10","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P11","name":"Phường 11","name_short":"11","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P12","name":"Phường 12","name_short":"12","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P13","name":"Phường 13","name_short":"13","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P14","name":"Phường 14","name_short":"14","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P15","name":"Phường 15","name_short":"15","type":"ward","parent_code":"VN-SG-TPhu"},
  {"code":"VN-SG-TPhu-P16","name":"Phường 16","name_short":"16","type":"ward","parent_code":"VN-SG-TPhu"},

  {"code":"VN-SG-BTan-ATay","name":"Phường An Lạc","name_short":"An Lạc","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-ATayA","name":"Phường An Lạc A","name_short":"An Lạc A","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTHDong","name":"Phường Bình Hưng Hòa","name_short":"Bình Hưng Hòa","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTHDongA","name":"Phường Bình Hưng Hòa A","name_short":"Bình Hưng Hòa A","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTHDongB","name":"Phường Bình Hưng Hòa B","name_short":"Bình Hưng Hòa B","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTTri","name":"Phường Bình Trị Đông","name_short":"Bình Trị Đông","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTTriA","name":"Phường Bình Trị Đông A","name_short":"Bình Trị Đông A","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-BTTriB","name":"Phường Bình Trị Đông B","name_short":"Bình Trị Đông B","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-ETao","name":"Phường Tân Tạo","name_short":"Tân Tạo","type":"ward","parent_code":"VN-SG-BTan"},
  {"code":"VN-SG-BTan-ETaoA","name":"Phường Tân Tạo A","name_short":"Tân Tạo A","type":"ward","parent_code":"VN-SG-BTan"},

  {"code":"VN-SG-ThuDuc-AKhanh","name":"Phường An Khánh","name_short":"An Khánh","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-ALDong","name":"Phường An Lợi Đông","name_short":"An Lợi Đông","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-APhu","name":"Phường An Phú","name_short":"An Phú","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-BAn","name":"Phường Bình An","name_short":"Bình An","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-BKhanh","name":"Phường Bình Khánh","name_short":"Bình Khánh","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-BTGDong","name":"Phường Bình Trưng Đông","name_short":"Bình Trưng Đông","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-BTGTay","name":"Phường Bình Trưng Tây","name_short":"Bình Trưng Tây","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-CLai","name":"Phường Cát Lái","name_short":"Cát Lái","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-HBinh","name":"Phường Hiệp Bình","name_short":"Hiệp Bình","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-HBChanh","name":"Phường Hiệp Bình Chánh","name_short":"Hiệp Bình Chánh","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-HBPhuoc","name":"Phường Hiệp Bình Phước","name_short":"Hiệp Bình Phước","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LChieu","name":"Phường Linh Chiểu","name_short":"Linh Chiểu","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LDong","name":"Phường Linh Đông","name_short":"Linh Đông","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LXuan","name":"Phường Linh Xuân","name_short":"Linh Xuân","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LTrung","name":"Phường Linh Trung","name_short":"Linh Trung","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LTBinh","name":"Phường Long Bình","name_short":"Long Bình","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LTMy","name":"Phường Long Thạnh Mỹ","name_short":"Long Thạnh Mỹ","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LPhuoc","name":"Phường Long Phước","name_short":"Long Phước","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-LTruong","name":"Phường Long Trường","name_short":"Long Trường","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-PBinh","name":"Phường Phú Hữu","name_short":"Phú Hữu","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-PLoc","name":"Phường Phước Long A","name_short":"Phước Long A","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-PLocB","name":"Phường Phước Long B","name_short":"Phước Long B","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-TMyLoi","name":"Phường Thạnh Mỹ Lợi","name_short":"Thạnh Mỹ Lợi","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-TPhu","name":"Phường Tân Phú","name_short":"Tân Phú","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-TBinh","name":"Phường Trường Thạnh","name_short":"Trường Thạnh","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-TBinhB","name":"Phường Tăng Nhơn Phú A","name_short":"Tăng Nhơn Phú A","type":"ward","parent_code":"VN-SG-ThuDuc"},
  {"code":"VN-SG-ThuDuc-TBinhC","name":"Phường Tăng Nhơn Phú B","name_short":"Tăng Nhơn Phú B","type":"ward","parent_code":"VN-SG-ThuDuc"},


  {"code":"VN-HN-HKiem-HBac","name":"Phường Hàng Bạc","name_short":"Hàng Bạc","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HBai","name":"Phường Hàng Bài","name_short":"Hàng Bài","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HBom","name":"Phường Hàng Bồ","name_short":"Hàng Bồ","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HBuom","name":"Phường Hàng Buồm","name_short":"Hàng Buồm","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HDao","name":"Phường Hàng Đào","name_short":"Hàng Đào","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HGai","name":"Phường Hàng Gai","name_short":"Hàng Gai","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HMa","name":"Phường Hàng Mã","name_short":"Hàng Mã","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-HTrong","name":"Phường Hàng Trống","name_short":"Hàng Trống","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-CDo","name":"Phường Chợ Dừa","name_short":"Chợ Dừa","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-DTien","name":"Phường Đồng Tiến","name_short":"Đồng Tiến","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-LLong","name":"Phường Lý Thái Tổ","name_short":"Lý Thái Tổ","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-PHChinh","name":"Phường Phạm Đình Hổ","name_short":"Phạm Đình Hổ","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-PSTra","name":"Phường Phúc Tân","name_short":"Phúc Tân","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-TTien","name":"Phường Trần Hưng Đạo","name_short":"Trần Hưng Đạo","type":"ward","parent_code":"VN-HN-HKiem"},
  {"code":"VN-HN-HKiem-TQT","name":"Phường Tràng Tiền","name_short":"Tràng Tiền","type":"ward","parent_code":"VN-HN-HKiem"},

  {"code":"VN-HN-BDinh-CVi","name":"Phường Cống Vị","name_short":"Cống Vị","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-DNoi","name":"Phường Điện Biên","name_short":"Điện Biên","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-DXa","name":"Phường Đội Cấn","name_short":"Đội Cấn","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-GTGo","name":"Phường Giảng Võ","name_short":"Giảng Võ","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-HBong","name":"Phường Hàng Bột","name_short":"Hàng Bột","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-KMai","name":"Phường Kim Mã","name_short":"Kim Mã","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-LDai","name":"Phường Liễu Giai","name_short":"Liễu Giai","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-NTL","name":"Phường Nguyễn Trung Trực","name_short":"Nguyễn Trung Trực","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-NTian","name":"Phường Nghĩa Đô","name_short":"Nghĩa Đô","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-PDLinh","name":"Phường Phúc Xá","name_short":"Phúc Xá","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-QTH","name":"Phường Quán Thánh","name_short":"Quán Thánh","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-TTMai","name":"Phường Thành Công","name_short":"Thành Công","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-TXC","name":"Phường Trúc Bạch","name_short":"Trúc Bạch","type":"ward","parent_code":"VN-HN-BDinh"},
  {"code":"VN-HN-BDinh-VP","name":"Phường Vĩnh Phúc","name_short":"Vĩnh Phúc","type":"ward","parent_code":"VN-HN-BDinh"},

  {"code":"VN-HN-DongDa-CDo","name":"Phường Chợ Dừa","name_short":"Chợ Dừa","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-CVong","name":"Phường Cát Linh","name_short":"Cát Linh","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-DDa","name":"Phường Đống Đa","name_short":"Đống Đa","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-HCH","name":"Phường Hàng Cháo","name_short":"Hàng Cháo","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-KLien","name":"Phường Kim Liên","name_short":"Kim Liên","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-KMai","name":"Phường Khâm Thiên","name_short":"Khâm Thiên","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-KThuong","name":"Phường Khương Thượng","name_short":"Khương Thượng","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-LChu","name":"Phường Láng Hạ","name_short":"Láng Hạ","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-LThuong","name":"Phường Láng Thượng","name_short":"Láng Thượng","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-NTS","name":"Phường Nam Đồng","name_short":"Nam Đồng","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-OTCh","name":"Phường Ô Chợ Dừa","name_short":"Ô Chợ Dừa","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-PMinh","name":"Phường Phương Liên","name_short":"Phương Liên","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-PMai","name":"Phường Phương Mai","name_short":"Phương Mai","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-QTH","name":"Phường Quang Trung","name_short":"Quang Trung","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-TPHai","name":"Phường Thịnh Quang","name_short":"Thịnh Quang","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-TCLinh","name":"Phường Trung Liệt","name_short":"Trung Liệt","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-TVN","name":"Phường Trung Phụng","name_short":"Trung Phụng","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-VS","name":"Phường Văn Miếu","name_short":"Văn Miếu","type":"ward","parent_code":"VN-HN-DongDa"},
  {"code":"VN-HN-DongDa-VChan","name":"Phường Vạn Thạnh","name_short":"Vạn Thạnh","type":"ward","parent_code":"VN-HN-DongDa"},

  {"code":"VN-HN-HBT-BCh","name":"Phường Bách Khoa","name_short":"Bách Khoa","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-BMai","name":"Phường Bạch Mai","name_short":"Bạch Mai","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-CDai","name":"Phường Cầu Dền","name_short":"Cầu Dền","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-DNhan","name":"Phường Đống Nhân","name_short":"Đống Nhân","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-DTam","name":"Phường Đồng Tâm","name_short":"Đồng Tâm","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-HBTrung","name":"Phường Hai Bà Trưng","name_short":"Hai Bà Trưng","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-LDai","name":"Phường Lê Đại Hành","name_short":"Lê Đại Hành","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-MDong","name":"Phường Minh Khai","name_short":"Minh Khai","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-NCT","name":"Phường Nguyễn Công Trứ","name_short":"Nguyễn Công Trứ","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-PTuan","name":"Phường Phạm Đình Hổ","name_short":"Phạm Đình Hổ","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-PCH","name":"Phường Phố Huế","name_short":"Phố Huế","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-QTrung","name":"Phường Quỳnh Lôi","name_short":"Quỳnh Lôi","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-TTien","name":"Phường Thanh Lương","name_short":"Thanh Lương","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-TNhon","name":"Phường Thanh Nhàn","name_short":"Thanh Nhàn","type":"ward","parent_code":"VN-HN-HBT"},
  {"code":"VN-HN-HBT-VTan","name":"Phường Vĩnh Tuy","name_short":"Vĩnh Tuy","type":"ward","parent_code":"VN-HN-HBT"},

  {"code":"VN-HN-HMai-DHo","name":"Phường Đại Kim","name_short":"Đại Kim","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-DNghia","name":"Phường Định Công","name_short":"Định Công","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-GPhu","name":"Phường Giáp Bát","name_short":"Giáp Bát","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-HVinh","name":"Phường Hoàng Liệt","name_short":"Hoàng Liệt","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-HVan","name":"Phường Hoàng Văn Thụ","name_short":"Hoàng Văn Thụ","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-LTC","name":"Phường Lĩnh Nam","name_short":"Lĩnh Nam","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-MDong","name":"Phường Mai Động","name_short":"Mai Động","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-PDong","name":"Phường Pháp Vân","name_short":"Pháp Vân","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-TMai","name":"Phường Tân Mai","name_short":"Tân Mai","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-TDong","name":"Phường Thanh Trì","name_short":"Thanh Trì","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-TPhong","name":"Phường Thịnh Liệt","name_short":"Thịnh Liệt","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-TVan","name":"Phường Trần Phú","name_short":"Trần Phú","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-TPDong","name":"Phường Tương Mai","name_short":"Tương Mai","type":"ward","parent_code":"VN-HN-HMai"},
  {"code":"VN-HN-HMai-YSV","name":"Phường Yên Sở","name_short":"Yên Sở","type":"ward","parent_code":"VN-HN-HMai"},

  {"code":"VN-HN-LBien-BLinh","name":"Phường Bồ Đề","name_short":"Bồ Đề","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-CTu","name":"Phường Cự Khối","name_short":"Cự Khối","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-DNhan","name":"Phường Đức Giang","name_short":"Đức Giang","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-GThuy","name":"Phường Gia Thụy","name_short":"Gia Thụy","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-GLam","name":"Phường Giang Biên","name_short":"Giang Biên","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-LBien","name":"Phường Long Biên","name_short":"Long Biên","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-NThuy","name":"Phường Ngọc Lâm","name_short":"Ngọc Lâm","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-NDao","name":"Phường Ngọc Thụy","name_short":"Ngọc Thụy","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-PDong","name":"Phường Phúc Đồng","name_short":"Phúc Đồng","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-PLoi","name":"Phường Phúc Lợi","name_short":"Phúc Lợi","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-SDo","name":"Phường Sài Đồng","name_short":"Sài Đồng","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-TBang","name":"Phường Thạch Bàn","name_short":"Thạch Bàn","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-TLong","name":"Phường Thượng Thanh","name_short":"Thượng Thanh","type":"ward","parent_code":"VN-HN-LBien"},
  {"code":"VN-HN-LBien-VHung","name":"Phường Việt Hưng","name_short":"Việt Hưng","type":"ward","parent_code":"VN-HN-LBien"},

  {"code":"VN-HN-CGiay-DMai","name":"Phường Dịch Vọng","name_short":"Dịch Vọng","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-DVHau","name":"Phường Dịch Vọng Hậu","name_short":"Dịch Vọng Hậu","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-MTri","name":"Phường Mai Dịch","name_short":"Mai Dịch","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-NKL","name":"Phường Nghĩa Đô","name_short":"Nghĩa Đô","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-NTan","name":"Phường Nghĩa Tân","name_short":"Nghĩa Tân","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-QHoa","name":"Phường Quan Hoa","name_short":"Quan Hoa","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-TVQuan","name":"Phường Trung Hòa","name_short":"Trung Hòa","type":"ward","parent_code":"VN-HN-CGiay"},
  {"code":"VN-HN-CGiay-YHoa","name":"Phường Yên Hòa","name_short":"Yên Hòa","type":"ward","parent_code":"VN-HN-CGiay"},

  {"code":"VN-HN-TXuan-HDinh","name":"Phường Hạ Đình","name_short":"Hạ Đình","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-KDai","name":"Phường Khương Đình","name_short":"Khương Đình","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-KMai","name":"Phường Khương Mai","name_short":"Khương Mai","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-KTrung","name":"Phường Khương Trung","name_short":"Khương Trung","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-KVien","name":"Phường Khương Viên","name_short":"Khương Viên","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-NTuan","name":"Phường Nhân Chính","name_short":"Nhân Chính","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-TDo","name":"Phường Phương Liệt","name_short":"Phương Liệt","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-TXuan","name":"Phường Thanh Xuân Bắc","name_short":"Thanh Xuân Bắc","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-TXuanN","name":"Phường Thanh Xuân Nam","name_short":"Thanh Xuân Nam","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-TXuanT","name":"Phường Thanh Xuân Trung","name_short":"Thanh Xuân Trung","type":"ward","parent_code":"VN-HN-TXuan"},
  {"code":"VN-HN-TXuan-TVQuan","name":"Phường Thượng Đình","name_short":"Thượng Đình","type":"ward","parent_code":"VN-HN-TXuan"},

  {"code":"VN-HN-HDong-BDong","name":"Phường Biên Giang","name_short":"Biên Giang","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-CTien","name":"Phường Dương Nội","name_short":"Dương Nội","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-CHai","name":"Phường Đồng Mai","name_short":"Đồng Mai","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-HCau","name":"Phường Hà Cầu","name_short":"Hà Cầu","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-KBien","name":"Phường Kiến Hưng","name_short":"Kiến Hưng","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-LLai","name":"Phường La Khê","name_short":"La Khê","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-MTrai","name":"Phường Mỗ Lao","name_short":"Mỗ Lao","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-NQyen","name":"Phường Nguyễn Trãi","name_short":"Nguyễn Trãi","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-PDong","name":"Phường Phú La","name_short":"Phú La","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-PLam","name":"Phường Phú Lương","name_short":"Phú Lương","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-PDong2","name":"Phường Phúc Đồng","name_short":"Phúc Đồng","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-QLA","name":"Phường Quốc Lộ A","name_short":"Quốc Lộ A","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-TDong","name":"Phường Vạn Phúc","name_short":"Vạn Phúc","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-VPhuc","name":"Phường Văn Quán","name_short":"Văn Quán","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-YNghia","name":"Phường Yên Nghĩa","name_short":"Yên Nghĩa","type":"ward","parent_code":"VN-HN-HDong"},
  {"code":"VN-HN-HDong-YPhuc","name":"Phường Yết Kiêu","name_short":"Yết Kiêu","type":"ward","parent_code":"VN-HN-HDong"},

  {"code":"VN-HN-BTLiem-CNoi","name":"Phường Cổ Nhuế 1","name_short":"Cổ Nhuế 1","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-CNoi2","name":"Phường Cổ Nhuế 2","name_short":"Cổ Nhuế 2","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-DXuan","name":"Phường Đông Ngạc","name_short":"Đông Ngạc","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-DTPhap","name":"Phường Đức Thắng","name_short":"Đức Thắng","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-LCHe","name":"Phường Liên Mạc","name_short":"Liên Mạc","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-MTrai","name":"Phường Minh Khai","name_short":"Minh Khai","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-PDien","name":"Phường Phú Diễn","name_short":"Phú Diễn","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-PMinh","name":"Phường Phúc Diễn","name_short":"Phúc Diễn","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-TPhuong","name":"Phường Tây Tựu","name_short":"Tây Tựu","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-TXuan","name":"Phường Thượng Cát","name_short":"Thượng Cát","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-TTLiem","name":"Phường Thụy Phương","name_short":"Thụy Phương","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-XDinh","name":"Phường Xuân Đỉnh","name_short":"Xuân Đỉnh","type":"ward","parent_code":"VN-HN-BTLiem"},
  {"code":"VN-HN-BTLiem-XTao","name":"Phường Xuân Tảo","name_short":"Xuân Tảo","type":"ward","parent_code":"VN-HN-BTLiem"},

  {"code":"VN-HN-NTLiem-CTu","name":"Phường Cầu Diễn","name_short":"Cầu Diễn","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-LHoa","name":"Phường Mễ Trì","name_short":"Mễ Trì","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-MTri","name":"Phường Mỹ Đình 1","name_short":"Mỹ Đình 1","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-MTri2","name":"Phường Mỹ Đình 2","name_short":"Mỹ Đình 2","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-PDo","name":"Phường Phú Đô","name_short":"Phú Đô","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-PMinh","name":"Phường Phương Canh","name_short":"Phương Canh","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-THQ","name":"Phường Tây Mỗ","name_short":"Tây Mỗ","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-THoa","name":"Phường Trung Văn","name_short":"Trung Văn","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-TDo","name":"Phường Từ Liêm","name_short":"Từ Liêm","type":"ward","parent_code":"VN-HN-NTLiem"},
  {"code":"VN-HN-NTLiem-XPSo","name":"Phường Xuân Phương","name_short":"Xuân Phương","type":"ward","parent_code":"VN-HN-NTLiem"},

  {"code":"VN-DN-HChau-BDong","name":"Phường Bình Hiên","name_short":"Bình Hiên","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-BThuan","name":"Phường Bình Thuận","name_short":"Bình Thuận","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HBinh","name":"Phường Hải Châu I","name_short":"Hải Châu I","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HBinh2","name":"Phường Hải Châu II","name_short":"Hải Châu II","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HQuang","name":"Phường Hòa Cường Bắc","name_short":"Hòa Cường Bắc","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HQuang2","name":"Phường Hòa Cường Nam","name_short":"Hòa Cường Nam","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HThuan","name":"Phường Hòa Thuận Đông","name_short":"Hòa Thuận Đông","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-HThuan2","name":"Phường Hòa Thuận Tây","name_short":"Hòa Thuận Tây","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-NBinh","name":"Phường Nam Dương","name_short":"Nam Dương","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-PHoa","name":"Phường Phước Ninh","name_short":"Phước Ninh","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-TCTr","name":"Phường Thanh Bình","name_short":"Thanh Bình","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-TQT","name":"Phường Thạch Thang","name_short":"Thạch Thang","type":"ward","parent_code":"VN-DN-HChau"},
  {"code":"VN-DN-HChau-TPhu","name":"Phường Thuận Phước","name_short":"Thuận Phước","type":"ward","parent_code":"VN-DN-HChau"},

  {"code":"VN-DN-TKhe-AKhe","name":"Phường An Khê","name_short":"An Khê","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-NDu","name":"Phường Chính Gián","name_short":"Chính Gián","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-HKhe","name":"Phường Hòa Khê","name_short":"Hòa Khê","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-TKhe","name":"Phường Tam Thuận","name_short":"Tam Thuận","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-THai","name":"Phường Tân Chính","name_short":"Tân Chính","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-TDong","name":"Phường Thạc Gián","name_short":"Thạc Gián","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-TD","name":"Phường Thanh Khê Đông","name_short":"Thanh Khê Đông","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-TD2","name":"Phường Thanh Khê Tây","name_short":"Thanh Khê Tây","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-VN","name":"Phường Vĩnh Trung","name_short":"Vĩnh Trung","type":"ward","parent_code":"VN-DN-TKhe"},
  {"code":"VN-DN-TKhe-XHa","name":"Phường Xuân Hà","name_short":"Xuân Hà","type":"ward","parent_code":"VN-DN-TKhe"},

  {"code":"VN-DN-STra-AMPhu","name":"Phường An Hải Bắc","name_short":"An Hải Bắc","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-AMPhu2","name":"Phường An Hải Đông","name_short":"An Hải Đông","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-AMPhu3","name":"Phường An Hải Tây","name_short":"An Hải Tây","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-MDong","name":"Phường Mân Thái","name_short":"Mân Thái","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-NHai","name":"Phường Nại Hiên Đông","name_short":"Nại Hiên Đông","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-PLoc","name":"Phường Phước Lộc","name_short":"Phước Lộc","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-STra","name":"Phường Sơn Trà","name_short":"Sơn Trà","type":"ward","parent_code":"VN-DN-STra"},
  {"code":"VN-DN-STra-TPhu","name":"Phường Thọ Quang","name_short":"Thọ Quang","type":"ward","parent_code":"VN-DN-STra"},

  {"code":"VN-DN-NHSon-HTuan","name":"Phường Hòa Hải","name_short":"Hòa Hải","type":"ward","parent_code":"VN-DN-NHSon"},
  {"code":"VN-DN-NHSon-HQy","name":"Phường Hòa Phát","name_short":"Hòa Phát","type":"ward","parent_code":"VN-DN-NHSon"},
  {"code":"VN-DN-NHSon-HQy2","name":"Phường Hòa Quý","name_short":"Hòa Quý","type":"ward","parent_code":"VN-DN-NHSon"},
  {"code":"VN-DN-NHSon-MAn","name":"Phường Mỹ An","name_short":"Mỹ An","type":"ward","parent_code":"VN-DN-NHSon"},
  {"code":"VN-DN-NHSon-KMy","name":"Phường Khuê Mỹ","name_short":"Khuê Mỹ","type":"ward","parent_code":"VN-DN-NHSon"},

  {"code":"VN-DN-LChieu-HKhe","name":"Phường Hòa Khánh Bắc","name_short":"Hòa Khánh Bắc","type":"ward","parent_code":"VN-DN-LChieu"},
  {"code":"VN-DN-LChieu-HKhe2","name":"Phường Hòa Khánh Nam","name_short":"Hòa Khánh Nam","type":"ward","parent_code":"VN-DN-LChieu"},
  {"code":"VN-DN-LChieu-HMinh","name":"Phường Hòa Minh","name_short":"Hòa Minh","type":"ward","parent_code":"VN-DN-LChieu"},
  {"code":"VN-DN-LChieu-LChieu","name":"Phường Liên Chiểu","name_short":"Liên Chiểu","type":"ward","parent_code":"VN-DN-LChieu"},
  {"code":"VN-DN-LChieu-NDuong","name":"Phường Thanh Khê","name_short":"Thanh Khê","type":"ward","parent_code":"VN-DN-LChieu"},

  {"code":"VN-DN-CLe-CLe","name":"Phường Cẩm Lệ","name_short":"Cẩm Lệ","type":"ward","parent_code":"VN-DN-CLe"},
  {"code":"VN-DN-CLe-HAn","name":"Phường Hòa An","name_short":"Hòa An","type":"ward","parent_code":"VN-DN-CLe"},
  {"code":"VN-DN-CLe-HPhat","name":"Phường Hòa Phát","name_short":"Hòa Phát","type":"ward","parent_code":"VN-DN-CLe"},
  {"code":"VN-DN-CLe-HTho","name":"Phường Hòa Thọ Đông","name_short":"Hòa Thọ Đông","type":"ward","parent_code":"VN-DN-CLe"},
  {"code":"VN-DN-CLe-HTho2","name":"Phường Hòa Thọ Tây","name_short":"Hòa Thọ Tây","type":"ward","parent_code":"VN-DN-CLe"},
  {"code":"VN-DN-CLe-KTrung","name":"Phường Khuê Trung","name_short":"Khuê Trung","type":"ward","parent_code":"VN-DN-CLe"},

  {"code":"VN-CT-NKieu-ABinh","name":"Phường An Bình","name_short":"An Bình","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-ACu","name":"Phường An Cư","name_short":"An Cư","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-ALac","name":"Phường An Lạc","name_short":"An Lạc","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-ANghiep","name":"Phường An Nghiệp","name_short":"An Nghiệp","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-AHoa","name":"Phường An Hòa","name_short":"An Hòa","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-APhu","name":"Phường An Phú","name_short":"An Phú","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-CKhanh","name":"Phường Cái Khế","name_short":"Cái Khế","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-HBinh","name":"Phường Hưng Lợi","name_short":"Hưng Lợi","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-TAn","name":"Phường Tân An","name_short":"Tân An","type":"ward","parent_code":"VN-CT-NKieu"},
  {"code":"VN-CT-NKieu-XKhanh","name":"Phường Xuân Khánh","name_short":"Xuân Khánh","type":"ward","parent_code":"VN-CT-NKieu"},

  {"code":"VN-CT-BThuy-BThuy","name":"Phường Bình Thủy","name_short":"Bình Thủy","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-CTrinh","name":"Phường An Thới","name_short":"An Thới","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-HTong","name":"Phường Trà An","name_short":"Trà An","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-TAn","name":"Phường Trà Nóc","name_short":"Trà Nóc","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-TLoc","name":"Phường Thới An Đông","name_short":"Thới An Đông","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-LBinh","name":"Phường Long Hòa","name_short":"Long Hòa","type":"ward","parent_code":"VN-CT-BThuy"},
  {"code":"VN-CT-BThuy-TBinh","name":"Phường Thới Ninh","name_short":"Thới Ninh","type":"ward","parent_code":"VN-CT-BThuy"},

  {"code":"VN-CT-CRang-BLinh","name":"Phường Ba Láng","name_short":"Ba Láng","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-HPhu","name":"Phường Hưng Phú","name_short":"Hưng Phú","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-HThach","name":"Phường Hưng Thạnh","name_short":"Hưng Thạnh","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-PPhu","name":"Phường Lê Bình","name_short":"Lê Bình","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-TPhu","name":"Phường Phú Thứ","name_short":"Phú Thứ","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-TThuan","name":"Phường Tân Hưng","name_short":"Tân Hưng","type":"ward","parent_code":"VN-CT-CRang"},
  {"code":"VN-CT-CRang-TPhu2","name":"Phường Thường Thạnh","name_short":"Thường Thạnh","type":"ward","parent_code":"VN-CT-CRang"},

  {"code":"VN-CT-OMon-CDo","name":"Phường Châu Văn Liêm","name_short":"Châu Văn Liêm","type":"ward","parent_code":"VN-CT-OMon"},
  {"code":"VN-CT-OMon-LHoa","name":"Phường Long Hưng","name_short":"Long Hưng","type":"ward","parent_code":"VN-CT-OMon"},
  {"code":"VN-CT-OMon-PhTho","name":"Phường Phước Thới","name_short":"Phước Thới","type":"ward","parent_code":"VN-CT-OMon"},
  {"code":"VN-CT-OMon-THoa","name":"Phường Thới An","name_short":"Thới An","type":"ward","parent_code":"VN-CT-OMon"},
  {"code":"VN-CT-OMon-TLoc","name":"Phường Thới Hòa","name_short":"Thới Hòa","type":"ward","parent_code":"VN-CT-OMon"},
  {"code":"VN-CT-OMon-TThuan","name":"Phường Trường Lạc","name_short":"Trường Lạc","type":"ward","parent_code":"VN-CT-OMon"},

  {"code":"VN-CT-TNot-TNot","name":"Phường Thốt Nốt","name_short":"Thốt Nốt","type":"ward","parent_code":"VN-CT-TNot"},
  {"code":"VN-CT-TNot-THai","name":"Phường Thới Thuận","name_short":"Thới Thuận","type":"ward","parent_code":"VN-CT-TNot"},
  {"code":"VN-CT-TNot-TAn","name":"Phường Thuận An","name_short":"Thuận An","type":"ward","parent_code":"VN-CT-TNot"},
  {"code":"VN-CT-TNot-TLoc","name":"Phường Thạnh Hòa","name_short":"Thạnh Hòa","type":"ward","parent_code":"VN-CT-TNot"},
  {"code":"VN-CT-TNot-TBinh","name":"Phường Trung Nhứt","name_short":"Trung Nhứt","type":"ward","parent_code":"VN-CT-TNot"},
  {"code":"VN-CT-TNot-TAn2","name":"Phường Tân Hưng","name_short":"Tân Hưng","type":"ward","parent_code":"VN-CT-TNot"},

  {"code":"VN-HP-HBang-HBang","name":"Phường Hồng Bàng","name_short":"Hồng Bàng","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-HPhong","name":"Phường Hạ Lý","name_short":"Hạ Lý","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-HDuc","name":"Phường Hoàng Văn Thụ","name_short":"Hoàng Văn Thụ","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-HP","name":"Phường Minh Khai","name_short":"Minh Khai","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-PHai","name":"Phường Phan Bội Châu","name_short":"Phan Bội Châu","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-QTrung","name":"Phường Quán Toan","name_short":"Quán Toan","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-STri","name":"Phường Sở Dầu","name_short":"Sở Dầu","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-THT","name":"Phường Thượng Lý","name_short":"Thượng Lý","type":"ward","parent_code":"VN-HP-HBang"},
  {"code":"VN-HP-HBang-TNT","name":"Phường Trại Chuối","name_short":"Trại Chuối","type":"ward","parent_code":"VN-HP-HBang"},

  {"code":"VN-HP-LChan-LChan","name":"Phường An Biên","name_short":"An Biên","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-ADong","name":"Phường An Dương","name_short":"An Dương","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-CTra","name":"Phường Cát Dài","name_short":"Cát Dài","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-DQuoc","name":"Phường Đông Hải","name_short":"Đông Hải","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-DHai","name":"Phường Dư Hàng","name_short":"Dư Hàng","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-HPhong","name":"Phường Hàng Kênh","name_short":"Hàng Kênh","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-HVUong","name":"Phường Hồ Nam","name_short":"Hồ Nam","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-KDong","name":"Phường Kênh Dương","name_short":"Kênh Dương","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-LChan2","name":"Phường Lạc Viên","name_short":"Lạc Viên","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-LChan3","name":"Phường Lương Khánh Thiện","name_short":"Lương Khánh Thiện","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-NND","name":"Phường Nghĩa Xá","name_short":"Nghĩa Xá","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-NHai","name":"Phường Niệm Nghĩa","name_short":"Niệm Nghĩa","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-THai","name":"Phường Trần Nguyên Hãn","name_short":"Trần Nguyên Hãn","type":"ward","parent_code":"VN-HP-LChan"},
  {"code":"VN-HP-LChan-TPhu","name":"Phường Vĩnh Niệm","name_short":"Vĩnh Niệm","type":"ward","parent_code":"VN-HP-LChan"},

  {"code":"VN-HP-NQuyen-CC","name":"Phường Cầu Đất","name_short":"Cầu Đất","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-CG","name":"Phường Cầu Tre","name_short":"Cầu Tre","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-DK","name":"Phường Đằng Giang","name_short":"Đằng Giang","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-DV","name":"Phường Đông Khê","name_short":"Đông Khê","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-GV","name":"Phường Gia Viên","name_short":"Gia Viên","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-LL","name":"Phường Lạch Tray","name_short":"Lạch Tray","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-LB","name":"Phường Lê Lợi","name_short":"Lê Lợi","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-MK","name":"Phường Máy Chai","name_short":"Máy Chai","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-MT","name":"Phường Máy Tơ","name_short":"Máy Tơ","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-QT","name":"Phường Quán Trữ","name_short":"Quán Trữ","type":"ward","parent_code":"VN-HP-NQuyen"},
  {"code":"VN-HP-NQuyen-VM","name":"Phường Vạn Mỹ","name_short":"Vạn Mỹ","type":"ward","parent_code":"VN-HP-NQuyen"},

  {"code":"VN-HP-KAn-BTra","name":"Phường Bắc Sơn","name_short":"Bắc Sơn","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-DHai","name":"Phường Đồng Hòa","name_short":"Đồng Hòa","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-LBinh","name":"Phường Lãm Hà","name_short":"Lãm Hà","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-LHai","name":"Phường Nam Sơn","name_short":"Nam Sơn","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-NSo","name":"Phường Ngọc Sơn","name_short":"Ngọc Sơn","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-PLinh","name":"Phường Phù Liễn","name_short":"Phù Liễn","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-QTra","name":"Phường Quán Trữ","name_short":"Quán Trữ","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-TTra","name":"Phường Trần Thành Ngọ","name_short":"Trần Thành Ngọ","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-TBinh","name":"Phường Tràng Minh","name_short":"Tràng Minh","type":"ward","parent_code":"VN-HP-KAn"},
  {"code":"VN-HP-KAn-VMy","name":"Phường Văn Đẩu","name_short":"Văn Đẩu","type":"ward","parent_code":"VN-HP-KAn"},

  {"code":"VN-HP-HAn-CHai","name":"Phường Cát Bi","name_short":"Cát Bi","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-DHai2","name":"Phường Đằng Hải","name_short":"Đằng Hải","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-DLinh","name":"Phường Đông Hải 1","name_short":"Đông Hải 1","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-HAn","name":"Phường Đông Hải 2","name_short":"Đông Hải 2","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-HAn2","name":"Phường Hải An","name_short":"Hải An","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-NAi","name":"Phường Nam Hải","name_short":"Nam Hải","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-TChai","name":"Phường Thành Tô","name_short":"Thành Tô","type":"ward","parent_code":"VN-HP-HAn"},
  {"code":"VN-HP-HAn-TBinh","name":"Phường Tràng Cát","name_short":"Tràng Cát","type":"ward","parent_code":"VN-HP-HAn"},

  {"code":"VN-HP-DSon-BSon","name":"Phường Bàng La","name_short":"Bàng La","type":"ward","parent_code":"VN-HP-DSon"},
  {"code":"VN-HP-DSon-HP","name":"Phường Hợp Đức","name_short":"Hợp Đức","type":"ward","parent_code":"VN-HP-DSon"},
  {"code":"VN-HP-DSon-MDong","name":"Phường Minh Đức","name_short":"Minh Đức","type":"ward","parent_code":"VN-HP-DSon"},
  {"code":"VN-HP-DSon-NDO","name":"Phường Ngọc Hải","name_short":"Ngọc Hải","type":"ward","parent_code":"VN-HP-DSon"},
  {"code":"VN-HP-DSon-VBinh","name":"Phường Vạn Hương","name_short":"Vạn Hương","type":"ward","parent_code":"VN-HP-DSon"},

  {"code":"VN-HP-DKinh-ATrai","name":"Phường Anh Dũng","name_short":"Anh Dũng","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-DKinh","name":"Phường Đa Phúc","name_short":"Đa Phúc","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-HDuc","name":"Phường Hải Thành","name_short":"Hải Thành","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-HNhan","name":"Phường Hòa Nghĩa","name_short":"Hòa Nghĩa","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-HPhong","name":"Phường Hưng Đạo","name_short":"Hưng Đạo","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-MDuc","name":"Phường Minh Đức","name_short":"Minh Đức","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-NHai","name":"Phường Nam Hải","name_short":"Nam Hải","type":"ward","parent_code":"VN-HP-DKinh"},
  {"code":"VN-HP-DKinh-TDuc","name":"Phường Tân Thành","name_short":"Tân Thành","type":"ward","parent_code":"VN-HP-DKinh"}
]'::json) AS x(code VARCHAR(20), name TEXT, name_short TEXT, type TEXT, level INTEGER, parent_code VARCHAR(20))
ON CONFLICT (code) DO NOTHING;
