-- Seed districts for 5 major cities (ward prerequisite)
-- HCMC, Hanoi, Da Nang, Can Tho, Hai Phong
INSERT INTO vietnam_administrative_divisions (code, name, name_short, type, level, parent_code)
SELECT code, name, name_short, type, COALESCE(level, 2), parent_code FROM json_to_recordset('[
  {"code":"VN-SG-Q1","name":"Quận 1","name_short":"1","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q2","name":"Quận 2","name_short":"2","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q3","name":"Quận 3","name_short":"3","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q4","name":"Quận 4","name_short":"4","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q5","name":"Quận 5","name_short":"5","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q6","name":"Quận 6","name_short":"6","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q7","name":"Quận 7","name_short":"7","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q8","name":"Quận 8","name_short":"8","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q9","name":"Quận 9","name_short":"9","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q10","name":"Quận 10","name_short":"10","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q11","name":"Quận 11","name_short":"11","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q12","name":"Quận 12","name_short":"12","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BThanh","name":"Quận Bình Thạnh","name_short":"Bình Thạnh","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-PNhuan","name":"Quận Phú Nhuận","name_short":"Phú Nhuận","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-GoVap","name":"Quận Gò Vấp","name_short":"Gò Vấp","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-TBinh","name":"Quận Tân Bình","name_short":"Tân Bình","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-TPhu","name":"Quận Tân Phú","name_short":"Tân Phú","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BTan","name":"Quận Bình Tân","name_short":"Bình Tân","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-ThuDuc","name":"Thành phố Thủ Đức","name_short":"Thủ Đức","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-HocMon","name":"Huyện Hóc Môn","name_short":"Hóc Môn","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BChan","name":"Huyện Bình Chánh","name_short":"Bình Chánh","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-NhaBe","name":"Huyện Nhà Bè","name_short":"Nhà Bè","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-CGio","name":"Huyện Cần Giờ","name_short":"Cần Giờ","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-CuChi","name":"Huyện Củ Chi","name_short":"Củ Chi","type":"district","parent_code":"VN-SG"},
  {"code":"VN-HN-HKiem","name":"Quận Hoàn Kiếm","name_short":"Hoàn Kiếm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-DongDa","name":"Quận Đống Đa","name_short":"Đống Đa","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-BDinh","name":"Quận Ba Đình","name_short":"Ba Đình","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HBT","name":"Quận Hai Bà Trưng","name_short":"Hai Bà Trưng","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HMai","name":"Quận Hoàng Mai","name_short":"Hoàng Mai","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-LBien","name":"Quận Long Biên","name_short":"Long Biên","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-CGiay","name":"Quận Cầu Giấy","name_short":"Cầu Giấy","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-TXuan","name":"Quận Thanh Xuân","name_short":"Thanh Xuân","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HDong","name":"Quận Hà Đông","name_short":"Hà Đông","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-BTLiem","name":"Quận Bắc Từ Liêm","name_short":"Bắc Từ Liêm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-NTLiem","name":"Quận Nam Từ Liêm","name_short":"Nam Từ Liêm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-DN-HChau","name":"Quận Hải Châu","name_short":"Hải Châu","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-TKhe","name":"Quận Thanh Khê","name_short":"Thanh Khê","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-STra","name":"Quận Sơn Trà","name_short":"Sơn Trà","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-NHSon","name":"Quận Ngũ Hành Sơn","name_short":"Ngũ Hành Sơn","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-LChieu","name":"Quận Liên Chiểu","name_short":"Liên Chiểu","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-CLe","name":"Quận Cẩm Lệ","name_short":"Cẩm Lệ","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-HVang","name":"Huyện Hòa Vang","name_short":"Hòa Vang","type":"district","parent_code":"VN-DN"},
  {"code":"VN-CT-NKieu","name":"Quận Ninh Kiều","name_short":"Ninh Kiều","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-BThuy","name":"Quận Bình Thủy","name_short":"Bình Thủy","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-CRang","name":"Quận Cái Răng","name_short":"Cái Răng","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-OMon","name":"Quận Ô Môn","name_short":"Ô Môn","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-TNot","name":"Quận Thốt Nốt","name_short":"Thốt Nốt","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-PDien","name":"Huyện Phong Điền","name_short":"Phong Điền","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-CDo","name":"Huyện Cờ Đỏ","name_short":"Cờ Đỏ","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-VThanh","name":"Huyện Vĩnh Thạnh","name_short":"Vĩnh Thạnh","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-TLai","name":"Huyện Thới Lai","name_short":"Thới Lai","type":"district","parent_code":"VN-CT"},
  {"code":"VN-HP-HBang","name":"Quận Hồng Bàng","name_short":"Hồng Bàng","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-LChan","name":"Quận Lê Chân","name_short":"Lê Chân","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-NQuyen","name":"Quận Ngô Quyền","name_short":"Ngô Quyền","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-KAn","name":"Quận Kiến An","name_short":"Kiến An","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-HAn","name":"Quận Hải An","name_short":"Hải An","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-DSon","name":"Quận Đồ Sơn","name_short":"Đồ Sơn","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-DKinh","name":"Quận Dương Kinh","name_short":"Dương Kinh","type":"district","parent_code":"VN-HP"}
]'::json) AS x(code VARCHAR(20), name TEXT, name_short TEXT, type TEXT, level INTEGER, parent_code VARCHAR(20))
ON CONFLICT (code) DO NOTHING;
