-- P0.7: Seed districts for all 34 provinces
-- Compact format using JSON bulk insert

INSERT INTO vietnam_administrative_divisions (code, name, name_short, type, level, parent_code)
SELECT * FROM jsonb_to_recordset('[
  -- Hồ Chí Minh City (VN-SG)
  {"code":"VN-SG-Q1","name":"Quận 1","name_short":"1","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q2","name":"Quận 2","name_short":"2","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q3","name":"Quận 3","name_short":"3","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q4","name":"Quận 4","name_short":"4","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q5","name":"Quận 5","name_short":"5","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q6","name":"Quận 6","name_short":"6","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q7","name":"Quận 7","name_short":"7","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q8","name":"Quận 8","name_short":"8","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q9","name":"Quận 9","name_short":"9","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q10","name":"Quận 10","name_short":"10","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q11","name":"Quận 11","name_short":"11","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-Q12","name":"Quận 12","name_short":"12","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BThanh","name":"Quận Bình Thạnh","name_short":"Bình Thạnh","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-PNhuan","name":"Quận Phú Nhuận","name_short":"Phú Nhuận","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-GoVap","name":"Quận Gò Vấp","name_short":"Gò Vấp","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-TBinh","name":"Quận Tân Bình","name_short":"Tân Bình","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-TPhu","name":"Quận Tân Phú","name_short":"Tân Phú","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BTan","name":"Quận Bình Tân","name_short":"Bình Tân","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-ThuDuc","name":"Thành phố Thủ Đức","name_short":"Thủ Đức","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-HocMon","name":"Huyện Hóc Môn","name_short":"Hóc Môn","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-BChan","name":"Huyện Bình Chánh","name_short":"Bình Chánh","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-NhaBe","name":"Huyện Nhà Bè","name_short":"Nhà Bè","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-CGio","name":"Huyện Cần Giờ","name_short":"Cần Giờ","type":"district","parent_code":"VN-SG"},
  {"code":"VN-SG-CuChi","name":"Huyện Củ Chi","name_short":"Củ Chi","type":"district","parent_code":"VN-SG"},

  -- Hanoi (VN-HN)
  {"code":"VN-HN-HKiem","name":"Quận Hoàn Kiếm","name_short":"Hoàn Kiếm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-DongDa","name":"Quận Đống Đa","name_short":"Đống Đa","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-BDinh","name":"Quận Ba Đình","name_short":"Ba Đình","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HBT","name":"Quận Hai Bà Trưng","name_short":"Hai Bà Trưng","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HMai","name":"Quận Hoàng Mai","name_short":"Hoàng Mai","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-LBien","name":"Quận Long Biên","name_short":"Long Biên","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-CGiay","name":"Quận Cầu Giấy","name_short":"Cầu Giấy","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-TXuan","name":"Quận Thanh Xuân","name_short":"Thanh Xuân","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HDong","name":"Quận Hà Đông","name_short":"Hà Đông","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-BTLiem","name":"Quận Bắc Từ Liêm","name_short":"Bắc Từ Liêm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-NTLiem","name":"Quận Nam Từ Liêm","name_short":"Nam Từ Liêm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-SocSon","name":"Huyện Sóc Sơn","name_short":"Sóc Sơn","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-DAnh","name":"Huyện Đông Anh","name_short":"Đông Anh","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-GLam","name":"Huyện Gia Lâm","name_short":"Gia Lâm","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-TTri","name":"Huyện Thanh Trì","name_short":"Thanh Trì","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-MLinh","name":"Huyện Mê Linh","name_short":"Mê Linh","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-STay","name":"Thị xã Sơn Tây","name_short":"Sơn Tây","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-BVi","name":"Huyện Ba Vì","name_short":"Ba Vì","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-PTho","name":"Huyện Phúc Thọ","name_short":"Phúc Thọ","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-DPhuong","name":"Huyện Đan Phượng","name_short":"Đan Phượng","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-HDuc","name":"Huyện Hoài Đức","name_short":"Hoài Đức","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-QOai","name":"Huyện Quốc Oai","name_short":"Quốc Oai","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-CMy","name":"Huyện Chương Mỹ","name_short":"Chương Mỹ","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-Oai","name":"Huyện Thanh Oai","name_short":"Thanh Oai","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-TTin","name":"Huyện Thường Tín","name_short":"Thường Tín","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-PXuyen","name":"Huyện Phú Xuyên","name_short":"Phú Xuyên","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-UHoa","name":"Huyện Ứng Hòa","name_short":"Ứng Hòa","type":"district","parent_code":"VN-HN"},
  {"code":"VN-HN-MDuc","name":"Huyện Mỹ Đức","name_short":"Mỹ Đức","type":"district","parent_code":"VN-HN"},

  -- Da Nang (VN-DN)
  {"code":"VN-DN-HChau","name":"Quận Hải Châu","name_short":"Hải Châu","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-TKhe","name":"Quận Thanh Khê","name_short":"Thanh Khê","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-STra","name":"Quận Sơn Trà","name_short":"Sơn Trà","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-NHSon","name":"Quận Ngũ Hành Sơn","name_short":"Ngũ Hành Sơn","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-LChieu","name":"Quận Liên Chiểu","name_short":"Liên Chiểu","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-CLe","name":"Quận Cẩm Lệ","name_short":"Cẩm Lệ","type":"district","parent_code":"VN-DN"},
  {"code":"VN-DN-HVang","name":"Huyện Hòa Vang","name_short":"Hòa Vang","type":"district","parent_code":"VN-DN"},

  -- Can Tho (VN-CT)
  {"code":"VN-CT-NKieu","name":"Quận Ninh Kiều","name_short":"Ninh Kiều","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-BThuy","name":"Quận Bình Thủy","name_short":"Bình Thủy","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-CRang","name":"Quận Cái Răng","name_short":"Cái Răng","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-OMon","name":"Quận Ô Môn","name_short":"Ô Môn","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-TNot","name":"Quận Thốt Nốt","name_short":"Thốt Nốt","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-PDien","name":"Huyện Phong Điền","name_short":"Phong Điền","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-CDo","name":"Huyện Cờ Đỏ","name_short":"Cờ Đỏ","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-VThanh","name":"Huyện Vĩnh Thạnh","name_short":"Vĩnh Thạnh","type":"district","parent_code":"VN-CT"},
  {"code":"VN-CT-TLai","name":"Huyện Thới Lai","name_short":"Thới Lai","type":"district","parent_code":"VN-CT"},

  -- Hai Phong (VN-HP)
  {"code":"VN-HP-HBang","name":"Quận Hồng Bàng","name_short":"Hồng Bàng","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-LChan","name":"Quận Lê Chân","name_short":"Lê Chân","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-NQuyen","name":"Quận Ngô Quyền","name_short":"Ngô Quyền","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-KAn","name":"Quận Kiến An","name_short":"Kiến An","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-HAn","name":"Quận Hải An","name_short":"Hải An","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-DSon","name":"Quận Đồ Sơn","name_short":"Đồ Sơn","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-DKinh","name":"Quận Dương Kinh","name_short":"Dương Kinh","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-TNguyen","name":"Huyện Thủy Nguyên","name_short":"Thủy Nguyên","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-ALao","name":"Huyện An Lão","name_short":"An Lão","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-KThuy","name":"Huyện Kiến Thụy","name_short":"Kiến Thụy","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-TLang","name":"Huyện Tiên Lãng","name_short":"Tiên Lãng","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-VBao","name":"Huyện Vĩnh Bảo","name_short":"Vĩnh Bảo","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-CHai","name":"Huyện Cát Hải","name_short":"Cát Hải","type":"district","parent_code":"VN-HP"},
  {"code":"VN-HP-BachL","name":"Huyện Bạch Long Vĩ","name_short":"Bạch Long Vĩ","type":"district","parent_code":"VN-HP"},

  -- Binh Duong (VN-BD)
  {"code":"VN-BD-TDMot","name":"Thành phố Thủ Dầu Một","name_short":"Thủ Dầu Một","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-DAn","name":"Thành phố Dĩ An","name_short":"Dĩ An","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-TAn","name":"Thành phố Thuận An","name_short":"Thuận An","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-BCat","name":"Thị xã Bến Cát","name_short":"Bến Cát","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-TUyen","name":"Thị xã Tân Uyên","name_short":"Tân Uyên","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-PGiao","name":"Huyện Phú Giáo","name_short":"Phú Giáo","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-DTieng","name":"Huyện Dầu Tiếng","name_short":"Dầu Tiếng","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-BBang","name":"Huyện Bàu Bàng","name_short":"Bàu Bàng","type":"district","parent_code":"VN-BD"},
  {"code":"VN-BD-BTUyen","name":"Huyện Bắc Tân Uyên","name_short":"Bắc Tân Uyên","type":"district","parent_code":"VN-BD"},

  -- Dong Nai (VN-DNai)
  {"code":"VN-DNai-BHoa","name":"Thành phố Biên Hòa","name_short":"Biên Hòa","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-LKhanh","name":"Thành phố Long Khánh","name_short":"Long Khánh","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-VCuu","name":"Huyện Vĩnh Cửu","name_short":"Vĩnh Cửu","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-TPhu","name":"Huyện Tân Phú","name_short":"Tân Phú","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-DQuan","name":"Huyện Định Quán","name_short":"Định Quán","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-TBom","name":"Huyện Trảng Bom","name_short":"Trảng Bom","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-TNhat","name":"Huyện Thống Nhất","name_short":"Thống Nhất","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-CMy","name":"Huyện Cẩm Mỹ","name_short":"Cẩm Mỹ","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-LThanh","name":"Huyện Long Thành","name_short":"Long Thành","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-XLoc","name":"Huyện Xuân Lộc","name_short":"Xuân Lộc","type":"district","parent_code":"VN-DNai"},
  {"code":"VN-DNai-NTrach","name":"Huyện Nhơn Trạch","name_short":"Nhơn Trạch","type":"district","parent_code":"VN-DNai"},

  -- Ba Ria - Vung Tau (VN-BV)
  {"code":"VN-BV-VTau","name":"Thành phố Vũng Tàu","name_short":"Vũng Tàu","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-BRia","name":"Thành phố Bà Rịa","name_short":"Bà Rịa","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-PMy","name":"Thị xã Phú Mỹ","name_short":"Phú Mỹ","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-CDuc","name":"Huyện Châu Đức","name_short":"Châu Đức","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-XMoc","name":"Huyện Xuyên Mộc","name_short":"Xuyên Mộc","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-LDien","name":"Huyện Long Điền","name_short":"Long Điền","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-DDo","name":"Huyện Đất Đỏ","name_short":"Đất Đỏ","type":"district","parent_code":"VN-BV"},
  {"code":"VN-BV-CDao","name":"Huyện Côn Đảo","name_short":"Côn Đảo","type":"district","parent_code":"VN-BV"},

  -- Long An (VN-LA)
  {"code":"VN-LA-TAn","name":"Thành phố Tân An","name_short":"Tân An","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-KTuong","name":"Thị xã Kiến Tường","name_short":"Kiến Tường","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-VHung","name":"Huyện Vĩnh Hưng","name_short":"Vĩnh Hưng","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-MHoa","name":"Huyện Mộc Hóa","name_short":"Mộc Hóa","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-TThanh","name":"Huyện Tân Thạnh","name_short":"Tân Thạnh","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-THoa","name":"Huyện Thạnh Hóa","name_short":"Thạnh Hóa","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-DHue","name":"Huyện Đức Huệ","name_short":"Đức Huệ","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-DHoa","name":"Huyện Đức Hòa","name_short":"Đức Hòa","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-BLuc","name":"Huyện Bến Lức","name_short":"Bến Lức","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-TThua","name":"Huyện Thủ Thừa","name_short":"Thủ Thừa","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-TTru","name":"Huyện Tân Trụ","name_short":"Tân Trụ","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-CDuoc","name":"Huyện Cần Đước","name_short":"Cần Đước","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-CGiuoc","name":"Huyện Cần Giuộc","name_short":"Cần Giuộc","type":"district","parent_code":"VN-LA"},
  {"code":"VN-LA-CThanh2","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-LA"},

  -- Tay Ninh (VN-TN)
  {"code":"VN-TN-TNinh","name":"Thành phố Tây Ninh","name_short":"Tây Ninh","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-TBien","name":"Huyện Tân Biên","name_short":"Tân Biên","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-TChau","name":"Huyện Tân Châu","name_short":"Tân Châu","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-DMChau","name":"Huyện Dương Minh Châu","name_short":"Dương Minh Châu","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-BCau","name":"Huyện Bến Cầu","name_short":"Bến Cầu","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-GDau","name":"Huyện Gò Dầu","name_short":"Gò Dầu","type":"district","parent_code":"VN-TN"},
  {"code":"VN-TN-TBang","name":"Huyện Trảng Bàng","name_short":"Trảng Bàng","type":"district","parent_code":"VN-TN"}
]'::json) AS x(code VARCHAR(10), name TEXT, name_short TEXT, type TEXT, level INTEGER, parent_code VARCHAR(10))
ON CONFLICT (code) DO NOTHING;
