-- P0.8: Seed remaining province capitals + key districts (compact format)

-- Helper: insert district if not exists
INSERT INTO vietnam_administrative_divisions (code, name, name_short, type, level, parent_code)
SELECT * FROM jsonb_to_recordset('[
  -- Bac Ninh (VN-BN)
  {"code":"VN-BN-BNinh","name":"Thành phố Bắc Ninh","name_short":"Bắc Ninh","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-TSon","name":"Thị xã Từ Sơn","name_short":"Từ Sơn","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-QVo","name":"Huyện Quế Võ","name_short":"Quế Võ","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-TDuong","name":"Huyện Tiên Du","name_short":"Tiên Du","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-YPhong","name":"Huyện Yên Phong","name_short":"Yên Phong","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-GBinh","name":"Huyện Gia Bình","name_short":"Gia Bình","type":"district","parent_code":"VN-BN"},
  {"code":"VN-BN-LTai","name":"Huyện Lương Tài","name_short":"Lương Tài","type":"district","parent_code":"VN-BN"},

  -- Hung Yen (VN-HY)
  {"code":"VN-HY-HYen","name":"Thành phố Hưng Yên","name_short":"Hưng Yên","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-VLam","name":"Huyện Văn Lâm","name_short":"Văn Lâm","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-VGiang","name":"Huyện Văn Giang","name_short":"Văn Giang","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-YMy","name":"Huyện Yên Mỹ","name_short":"Yên Mỹ","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-MHao","name":"Thị xã Mỹ Hào","name_short":"Mỹ Hào","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-ALu","name":"Huyện Ân Thi","name_short":"Ân Thi","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-KChau","name":"Huyện Khoái Châu","name_short":"Khoái Châu","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-KDong","name":"Huyện Kim Động","name_short":"Kim Động","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-TTruong","name":"Huyện Tiên Lữ","name_short":"Tiên Lữ","type":"district","parent_code":"VN-HY"},
  {"code":"VN-HY-PhuCu","name":"Huyện Phù Cừ","name_short":"Phù Cừ","type":"district","parent_code":"VN-HY"},

  -- Hai Duong (VN-HD)
  {"code":"VN-HD-HDuong","name":"Thành phố Hải Dương","name_short":"Hải Dương","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-CLinh","name":"Thành phố Chí Linh","name_short":"Chí Linh","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-NGiang","name":"Thị xã Kinh Môn","name_short":"Kinh Môn","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-BGiang","name":"Huyện Bình Giang","name_short":"Bình Giang","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-CThanh","name":"Huyện Cẩm Giàng","name_short":"Cẩm Giàng","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-TLinh","name":"Huyện Thanh Hà","name_short":"Thanh Hà","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-KSach","name":"Huyện Kim Thành","name_short":"Kim Thành","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-NThanh","name":"Huyện Nam Sách","name_short":"Nam Sách","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-NGiang","name":"Huyện Ninh Giang","name_short":"Ninh Giang","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-GLoc","name":"Huyện Gia Lộc","name_short":"Gia Lộc","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-TMien","name":"Huyện Tứ Kỳ","name_short":"Tứ Kỳ","type":"district","parent_code":"VN-HD"},
  {"code":"VN-HD-TThuy","name":"Huyện Thanh Miện","name_short":"Thanh Miện","type":"district","parent_code":"VN-HD"},

  -- Vinh Phuc (VN-VP)
  {"code":"VN-VP-VYen","name":"Thành phố Vĩnh Yên","name_short":"Vĩnh Yên","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-PYen","name":"Thành phố Phúc Yên","name_short":"Phúc Yên","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-LThinh","name":"Huyện Lập Thạch","name_short":"Lập Thạch","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-TDuong","name":"Huyện Tam Dương","name_short":"Tam Dương","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-TDao","name":"Huyện Tam Đảo","name_short":"Tam Đảo","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-BXuyen","name":"Huyện Bình Xuyên","name_short":"Bình Xuyên","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-YLac","name":"Huyện Yên Lạc","name_short":"Yên Lạc","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-VTuong","name":"Huyện Vĩnh Tường","name_short":"Vĩnh Tường","type":"district","parent_code":"VN-VP"},
  {"code":"VN-VP-SLoi","name":"Huyện Sông Lô","name_short":"Sông Lô","type":"district","parent_code":"VN-VP"},

  -- Quang Ninh (VN-QN)
  {"code":"VN-QN-HLong","name":"Thành phố Hạ Long","name_short":"Hạ Long","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-CPha","name":"Thành phố Cẩm Phả","name_short":"Cẩm Phả","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-UBi","name":"Thành phố Uông Bí","name_short":"Uông Bí","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-MCai","name":"Thành phố Móng Cái","name_short":"Móng Cái","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-DTrieu","name":"Thị xã Đông Triều","name_short":"Đông Triều","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-QYen","name":"Thị xã Quảng Yên","name_short":"Quảng Yên","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-BLieu","name":"Huyện Bình Liêu","name_short":"Bình Liêu","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-TLinh","name":"Huyện Tiên Yên","name_short":"Tiên Yên","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-DHa","name":"Huyện Đầm Hà","name_short":"Đầm Hà","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-HHai","name":"Huyện Hải Hà","name_short":"Hải Hà","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-BCo","name":"Huyện Ba Chẽ","name_short":"Ba Chẽ","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-VDon","name":"Huyện Vân Đồn","name_short":"Vân Đồn","type":"district","parent_code":"VN-QN"},
  {"code":"VN-QN-CTrai","name":"Huyện Cô Tô","name_short":"Cô Tô","type":"district","parent_code":"VN-QN"},

  -- Quang Nam (VN-QNam)
  {"code":"VN-QNam-TKy","name":"Thành phố Tam Kỳ","name_short":"Tam Kỳ","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-HAn","name":"Thành phố Hội An","name_short":"Hội An","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-DBan","name":"Huyện Duy Xuyên","name_short":"Duy Xuyên","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-DGiang","name":"Huyện Đại Lộc","name_short":"Đại Lộc","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-DPhuoc","name":"Huyện Điện Bàn","name_short":"Điện Bàn","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-NThanh","name":"Huyện Núi Thành","name_short":"Núi Thành","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-TBinh","name":"Huyện Thăng Bình","name_short":"Thăng Bình","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-QSon","name":"Huyện Quế Sơn","name_short":"Quế Sơn","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-HDuc","name":"Huyện Hiệp Đức","name_short":"Hiệp Đức","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-NSon","name":"Huyện Nam Giang","name_short":"Nam Giang","type":"district","parent_code":"VN-QNam"},
  {"code":"VN-QNam-PNinh","name":"Huyện Phú Ninh","name_short":"Phú Ninh","type":"district","parent_code":"VN-QNam"},

  -- Khanh Hoa (VN-KH)
  {"code":"VN-KH-NTrang","name":"Thành phố Nha Trang","name_short":"Nha Trang","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-CHoa","name":"Thành phố Cam Ranh","name_short":"Cam Ranh","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-NHoa","name":"Thị xã Ninh Hòa","name_short":"Ninh Hòa","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-VNinh","name":"Huyện Vạn Ninh","name_short":"Vạn Ninh","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-DKhanh","name":"Huyện Diên Khánh","name_short":"Diên Khánh","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-KSon","name":"Huyện Khánh Vĩnh","name_short":"Khánh Vĩnh","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-KSOn","name":"Huyện Khánh Sơn","name_short":"Khánh Sơn","type":"district","parent_code":"VN-KH"},
  {"code":"VN-KH-TSau","name":"Huyện Trường Sa","name_short":"Trường Sa","type":"district","parent_code":"VN-KH"},

  -- An Giang (VN-AG)
  {"code":"VN-AG-LXuyen","name":"Thành phố Long Xuyên","name_short":"Long Xuyên","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-CDao","name":"Thành phố Châu Đốc","name_short":"Châu Đốc","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-ADao","name":"Thị xã An Phú","name_short":"An Phú","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-TChau","name":"Thị xã Tân Châu","name_short":"Tân Châu","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-PHoa","name":"Huyện Phú Tân","name_short":"Phú Tân","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-CPhu","name":"Huyện Châu Phú","name_short":"Châu Phú","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-TTT","name":"Huyện Tịnh Biên","name_short":"Tịnh Biên","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-TSon","name":"Huyện Tri Tôn","name_short":"Tri Tôn","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-CT","name":"Huyện Chợ Mới","name_short":"Chợ Mới","type":"district","parent_code":"VN-AG"},
  {"code":"VN-AG-TThanh","name":"Huyện Thoại Sơn","name_short":"Thoại Sơn","type":"district","parent_code":"VN-AG"},

  -- Kien Giang (VN-KG)
  {"code":"VN-KG-RGia","name":"Thành phố Rạch Giá","name_short":"Rạch Giá","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-HTien","name":"Thành phố Hà Tiên","name_short":"Hà Tiên","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-PQuoc","name":"Thành phố Phú Quốc","name_short":"Phú Quốc","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-VThuan","name":"Huyện Vĩnh Thuận","name_short":"Vĩnh Thuận","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-ABien","name":"Huyện An Biên","name_short":"An Biên","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-AMinh","name":"Huyện An Minh","name_short":"An Minh","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-GQuao","name":"Huyện Giồng Riềng","name_short":"Giồng Riềng","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-HDuc","name":"Huyện Hòn Đất","name_short":"Hòn Đất","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-KLai","name":"Huyện Kiên Lương","name_short":"Kiên Lương","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-PHoa","name":"Huyện Tân Hiệp","name_short":"Tân Hiệp","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-UBien","name":"Huyện U Minh Thượng","name_short":"U Minh Thượng","type":"district","parent_code":"VN-KG"},
  {"code":"VN-KG-GThanh","name":"Huyện Giang Thành","name_short":"Giang Thành","type":"district","parent_code":"VN-KG"},

  -- Tien Giang (VN-TG)
  {"code":"VN-TG-MTho","name":"Thành phố Mỹ Tho","name_short":"Mỹ Tho","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-GCong","name":"Thị xã Gò Công","name_short":"Gò Công","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-CLay","name":"Thị xã Cai Lậy","name_short":"Cai Lậy","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-THoa","name":"Huyện Tân Phước","name_short":"Tân Phước","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-CBe","name":"Huyện Chợ Gạo","name_short":"Chợ Gạo","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-GCTay","name":"Huyện Gò Công Tây","name_short":"Gò Công Tây","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-GCDong","name":"Huyện Gò Công Đông","name_short":"Gò Công Đông","type":"district","parent_code":"VN-TG"},
  {"code":"VN-TG-TLy","name":"Huyện Cái Bè","name_short":"Cái Bè","type":"district","parent_code":"VN-TG"},

  -- Ben Tre (VN-BT)
  {"code":"VN-BT-BTre","name":"Thành phố Bến Tre","name_short":"Bến Tre","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-CTrach","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-CLach","name":"Huyện Chợ Lách","name_short":"Chợ Lách","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-MHoa","name":"Huyện Mỏ Cày Nam","name_short":"Mỏ Cày Nam","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-GTrom","name":"Huyện Giồng Trôm","name_short":"Giồng Trôm","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-BTri","name":"Huyện Bình Đại","name_short":"Bình Đại","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-PHiep","name":"Huyện Phú Tân","name_short":"Phú Tân","type":"district","parent_code":"VN-BT"},
  {"code":"VN-BT-TPhu","name":"Huyện Thạnh Phú","name_short":"Thạnh Phú","type":"district","parent_code":"VN-BT"},

  -- Vinh Long (VN-VL)
  {"code":"VN-VL-VLong","name":"Thành phố Vĩnh Long","name_short":"Vĩnh Long","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-BMinh","name":"Huyện Bình Minh","name_short":"Bình Minh","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-TOn","name":"Huyện Tam Bình","name_short":"Tam Bình","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-TraOn","name":"Huyện Trà Ôn","name_short":"Trà Ôn","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-VLiem","name":"Huyện Vũng Liêm","name_short":"Vũng Liêm","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-MHoa","name":"Huyện Mang Thít","name_short":"Mang Thít","type":"district","parent_code":"VN-VL"},
  {"code":"VN-VL-BTan","name":"Huyện Long Hồ","name_short":"Long Hồ","type":"district","parent_code":"VN-VL"},

  -- Dong Thap (VN-DT)
  {"code":"VN-DT-CTho","name":"Thành phố Cao Lãnh","name_short":"Cao Lãnh","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-SDec","name":"Thành phố Sa Đéc","name_short":"Sa Đéc","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-HNgung","name":"Thành phố Hồng Ngự","name_short":"Hồng Ngự","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-THu","name":"Huyện Tân Hồng","name_short":"Tân Hồng","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-TTra","name":"Huyện Tam Nông","name_short":"Tam Nông","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-TMuoi","name":"Huyện Tháp Mười","name_short":"Tháp Mười","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-CLanh","name":"Huyện Cao Lãnh","name_short":"Cao Lãnh","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-LVo","name":"Huyện Lấp Vò","name_short":"Lấp Vò","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-LVu","name":"Huyện Lai Vung","name_short":"Lai Vung","type":"district","parent_code":"VN-DT"},
  {"code":"VN-DT-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-DT"},

  -- Ca Mau (VN-CM)
  {"code":"VN-CM-CMau","name":"Thành phố Cà Mau","name_short":"Cà Mau","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-UDong","name":"Huyện U Minh","name_short":"U Minh","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-TBinh","name":"Huyện Thới Bình","name_short":"Thới Bình","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-TDu","name":"Huyện Trần Văn Thời","name_short":"Trần Văn Thời","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-CHoi","name":"Huyện Cái Nước","name_short":"Cái Nước","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-DDong","name":"Huyện Đầm Dơi","name_short":"Đầm Dơi","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-NCan","name":"Huyện Năm Căn","name_short":"Năm Căn","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-PTan","name":"Huyện Phú Tân","name_short":"Phú Tân","type":"district","parent_code":"VN-CM"},
  {"code":"VN-CM-NHoi","name":"Huyện Ngọc Hiển","name_short":"Ngọc Hiển","type":"district","parent_code":"VN-CM"},

  -- Soc Trang (VN-ST)
  {"code":"VN-ST-STrang","name":"Thành phố Sóc Trăng","name_short":"Sóc Trăng","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-CKe","name":"Huyện Kế Sách","name_short":"Kế Sách","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-CThanh","name":"Huyện Châu Thành","name_short":"Châu Thành","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-MXuyen","name":"Huyện Mỹ Tú","name_short":"Mỹ Tú","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-MXuyen2","name":"Huyện Mỹ Xuyên","name_short":"Mỹ Xuyên","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-TVien","name":"Huyện Thạnh Trị","name_short":"Thạnh Trị","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-LNgan","name":"Huyện Long Phú","name_short":"Long Phú","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-CDo","name":"Huyện Cù Lao Dung","name_short":"Cù Lao Dung","type":"district","parent_code":"VN-ST"},
  {"code":"VN-ST-NNam","name":"Huyện Ngã Năm","name_short":"Ngã Năm","type":"district","parent_code":"VN-ST"},

  -- Bac Lieu (VN-BL)
  {"code":"VN-BL-BLieu","name":"Thành phố Bạc Liêu","name_short":"Bạc Liêu","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-HDan","name":"Huyện Hòa Bình","name_short":"Hòa Bình","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-VLoi","name":"Huyện Vĩnh Lợi","name_short":"Vĩnh Lợi","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-PLong","name":"Huyện Phước Long","name_short":"Phước Long","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-DHai","name":"Huyện Đông Hải","name_short":"Đông Hải","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-GRai","name":"Huyện Giá Rai","name_short":"Giá Rai","type":"district","parent_code":"VN-BL"},
  {"code":"VN-BL-HDan2","name":"Huyện Hồng Dân","name_short":"Hồng Dân","type":"district","parent_code":"VN-BL"},

  -- Lam Dong (VN-LD)
  {"code":"VN-LD-DTrong","name":"Thành phố Đà Lạt","name_short":"Đà Lạt","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-BLoc","name":"Thành phố Bảo Lộc","name_short":"Bảo Lộc","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-DHoa","name":"Huyện Đức Trọng","name_short":"Đức Trọng","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-DLinh","name":"Huyện Di Linh","name_short":"Di Linh","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-BLam","name":"Huyện Bảo Lâm","name_short":"Bảo Lâm","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-LDuong","name":"Huyện Lạc Dương","name_short":"Lạc Dương","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-DDon","name":"Huyện Đơn Dương","name_short":"Đơn Dương","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-DLinh","name":"Huyện Đạ Huoai","name_short":"Đạ Huoai","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-CTay","name":"Huyện Cát Tiên","name_short":"Cát Tiên","type":"district","parent_code":"VN-LD"},
  {"code":"VN-LD-LamHa","name":"Huyện Lâm Hà","name_short":"Lâm Hà","type":"district","parent_code":"VN-LD"},

  -- Dak Lak (VN-DL)
  {"code":"VN-DL-BMT","name":"Thành phố Buôn Ma Thuột","name_short":"Buôn Ma Thuột","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-BHo","name":"Thị xã Buôn Hồ","name_short":"Buôn Hồ","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-EHLeo","name":"Huyện Ea H'Leo","name_short":"Ea H'Leo","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-ECar","name":"Huyện Ea Kar","name_short":"Ea Kar","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-MDak","name":"Huyện M'Đrắk","name_short":"M'Đrắk","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-KNang","name":"Huyện Krông Năng","name_short":"Krông Năng","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-KBuk","name":"Huyện Krông Búk","name_short":"Krông Búk","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-KPac","name":"Huyện Krông Pắc","name_short":"Krông Pắc","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-KAna","name":"Huyện Krông Ana","name_short":"Krông Ana","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-KNang","name":"Huyện Krông Bông","name_short":"Krông Bông","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-CuMgar","name":"Huyện Cư M'Gar","name_short":"Cư M'Gar","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-EaSup","name":"Huyện Ea Súp","name_short":"Ea Súp","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-CuKuin","name":"Huyện Cư Kuin","name_short":"Cư Kuin","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-BDon","name":"Huyện Buôn Đôn","name_short":"Buôn Đôn","type":"district","parent_code":"VN-DL"},
  {"code":"VN-DL-Lak","name":"Huyện Lắk","name_short":"Lắk","type":"district","parent_code":"VN-DL"},

  -- Gia Lai (VN-GL)
  {"code":"VN-GL-PLieu","name":"Thành phố Pleiku","name_short":"Pleiku","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-ATB","name":"Thị xã An Khê","name_short":"An Khê","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-AYa","name":"Thị xã Ayun Pa","name_short":"Ayun Pa","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-KPa","name":"Huyện Kông Chro","name_short":"Kông Chro","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-DCao","name":"Huyện Đức Cơ","name_short":"Đức Cơ","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-CSu","name":"Huyện Chư Sê","name_short":"Chư Sê","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-CPuh","name":"Huyện Chư Pưh","name_short":"Chư Pưh","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-CProng","name":"Huyện Chư Prông","name_short":"Chư Prông","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-PThien","name":"Huyện Phú Thiện","name_short":"Phú Thiện","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-KBang","name":"Huyện KBang","name_short":"KBang","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-DDoa","name":"Huyện Đắk Đoa","name_short":"Đắk Đoa","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-IPa","name":"Huyện Ia Pa","name_short":"Ia Pa","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-IGrai","name":"Huyện Ia Grai","name_short":"Ia Grai","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-MYang","name":"Huyện Mang Yang","name_short":"Mang Yang","type":"district","parent_code":"VN-GL"},
  {"code":"VN-GL-KroPa","name":"Huyện Krông Pa","name_short":"Krông Pa","type":"district","parent_code":"VN-GL"},

  -- Kon Tum (VN-KT)
  {"code":"VN-KT-KTum","name":"Thành phố Kon Tum","name_short":"Kon Tum","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-DGLey","name":"Huyện Đắk Glei","name_short":"Đắk Glei","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-DTo","name":"Huyện Đắk Tô","name_short":"Đắk Tô","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-DLong","name":"Huyện Đắk Hà","name_short":"Đắk Hà","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-NHoi","name":"Huyện Ngọc Hồi","name_short":"Ngọc Hồi","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-KRay","name":"Huyện Kon Rẫy","name_short":"Kon Rẫy","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-TMoRong","name":"Huyện Tu Mơ Rông","name_short":"Tu Mơ Rông","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-SonTay","name":"Huyện Sa Thầy","name_short":"Sa Thầy","type":"district","parent_code":"VN-KT"},
  {"code":"VN-KT-IHD","name":"Huyện Ia H'Drai","name_short":"Ia H'Drai","type":"district","parent_code":"VN-KT"},

  -- Nghe An (VN-NA)
  {"code":"VN-NA-Vinh","name":"Thành phố Vinh","name_short":"Vinh","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-CLo","name":"Thị xã Cửa Lò","name_short":"Cửa Lò","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-TKy","name":"Thị xã Thái Hòa","name_short":"Thái Hòa","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-HNguyen","name":"Huyện Hưng Nguyên","name_short":"Hưng Nguyên","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-NLoc","name":"Huyện Nam Đàn","name_short":"Nam Đàn","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-NDan","name":"Huyện Nghi Lộc","name_short":"Nghi Lộc","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-DChau","name":"Huyện Diễn Châu","name_short":"Diễn Châu","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-QChau","name":"Huyện Quỳnh Lưu","name_short":"Quỳnh Lưu","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-NDan","name":"Huyện Yên Thành","name_short":"Yên Thành","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-CHuong","name":"Huyện Con Cuông","name_short":"Con Cuông","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-TDuong","name":"Huyện Tương Dương","name_short":"Tương Dương","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-KSon","name":"Huyện Kỳ Sơn","name_short":"Kỳ Sơn","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-QHop","name":"Huyện Quỳ Hợp","name_short":"Quỳ Hợp","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-QPhong","name":"Huyện Quế Phong","name_short":"Quế Phong","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-AT","name":"Huyện Anh Sơn","name_short":"Anh Sơn","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-THoa","name":"Huyện Thanh Chương","name_short":"Thanh Chương","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-NA","name":"Huyện Nghĩa Đàn","name_short":"Nghĩa Đàn","type":"district","parent_code":"VN-NA"},
  {"code":"VN-NA-QChau","name":"Huyện Quỳ Châu","name_short":"Quỳ Châu","type":"district","parent_code":"VN-NA"},

  -- Thanh Hoa (VN-TH)
  {"code":"VN-TH-THoa","name":"Thành phố Thanh Hóa","name_short":"Thanh Hóa","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-SSon","name":"Thị xã Sầm Sơn","name_short":"Sầm Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-BSon","name":"Thị xã Bỉm Sơn","name_short":"Bỉm Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NSon","name":"Thị xã Nghi Sơn","name_short":"Nghi Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-HHoa","name":"Huyện Hoằng Hóa","name_short":"Hoằng Hóa","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-QLu","name":"Huyện Quảng Xương","name_short":"Quảng Xương","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-DSon","name":"Huyện Đông Sơn","name_short":"Đông Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-HTrung","name":"Huyện Hà Trung","name_short":"Hà Trung","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NCong","name":"Huyện Nga Sơn","name_short":"Nga Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-Hoa","name":"Huyện Hậu Lộc","name_short":"Hậu Lộc","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NLoc","name":"Huyện Nông Cống","name_short":"Nông Cống","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-VLoc","name":"Huyện Vĩnh Lộc","name_short":"Vĩnh Lộc","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-TSach","name":"Huyện Thạch Thành","name_short":"Thạch Thành","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-CSon","name":"Huyện Cẩm Thủy","name_short":"Cẩm Thủy","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-BThuong","name":"Huyện Bá Thước","name_short":"Bá Thước","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-QHoa","name":"Huyện Quan Hóa","name_short":"Quan Hóa","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NXuan","name":"Huyện Như Xuân","name_short":"Như Xuân","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-MLat","name":"Huyện Mường Lát","name_short":"Mường Lát","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-THoa","name":"Huyện Triệu Sơn","name_short":"Triệu Sơn","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-TXuan","name":"Huyện Thọ Xuân","name_short":"Thọ Xuân","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NThanh","name":"Huyện Như Thanh","name_short":"Như Thanh","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-NCQuan","name":"Huyện Ngọc Lặc","name_short":"Ngọc Lặc","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-LThuong","name":"Huyện Lang Chánh","name_short":"Lang Chánh","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-THoa","name":"Huyện Thiệu Hóa","name_short":"Thiệu Hóa","type":"district","parent_code":"VN-TH"},
  {"code":"VN-TH-QSon","name":"Huyện Quan Sơn","name_short":"Quan Sơn","type":"district","parent_code":"VN-TH"},

  -- Thua Thien Hue (VN-TTH)
  {"code":"VN-TTH-Hue","name":"Thành phố Huế","name_short":"Huế","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-HThuy","name":"Thị xã Hương Thủy","name_short":"Hương Thủy","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-HTra","name":"Thị xã Hương Trà","name_short":"Hương Trà","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-PhongD","name":"Huyện Phong Điền","name_short":"Phong Điền","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-PLoc","name":"Huyện Phú Lộc","name_short":"Phú Lộc","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-PVang","name":"Huyện Phú Vang","name_short":"Phú Vang","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-QDien","name":"Huyện Quảng Điền","name_short":"Quảng Điền","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-ATu","name":"Huyện A Lưới","name_short":"A Lưới","type":"district","parent_code":"VN-TTH"},
  {"code":"VN-TTH-NamDong","name":"Huyện Nam Đông","name_short":"Nam Đông","type":"district","parent_code":"VN-TTH"},

  -- Binh Thuan (VN-BTh)
  {"code":"VN-BTh-PThiet","name":"Thành phố Phan Thiết","name_short":"Phan Thiết","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-LGi","name":"Thị xã La Gi","name_short":"La Gi","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-TLinh","name":"Huyện Tuy Phong","name_short":"Tuy Phong","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-BBinh","name":"Huyện Bắc Bình","name_short":"Bắc Bình","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-HThuan","name":"Huyện Hàm Thuận Bắc","name_short":"Hàm Thuận Bắc","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-HThuan2","name":"Huyện Hàm Thuận Nam","name_short":"Hàm Thuận Nam","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-HTan","name":"Huyện Hàm Tân","name_short":"Hàm Tân","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-DLinh","name":"Huyện Đức Linh","name_short":"Đức Linh","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-TLinh","name":"Huyện Tánh Linh","name_short":"Tánh Linh","type":"district","parent_code":"VN-BTh"},
  {"code":"VN-BTh-PhuQuy","name":"Huyện Phú Quý","name_short":"Phú Quý","type":"district","parent_code":"VN-BTh"}
]'::json) AS x(code VARCHAR(10), name TEXT, name_short TEXT, type TEXT, level INTEGER, parent_code VARCHAR(10))
ON CONFLICT (code) DO NOTHING;
